### PR TITLE
Alternative website design

### PR DESCRIPTION
**Pull request by cpfiffer**
This PR revises the website to use our current branding. It's only cosmetic, the same four actions (blog, github, hiring, json beta)

image

and on mobile: 

image

The current website looks like this:

image

Any suggestions or improvements?

### CODE REVIEW

**Comment by rlouf** [comment]
It's great! The only thing is that it renders this way in my browser:

webpage

**Comment by cpfiffer** [comment]
I tidied up the break points and fixed the smushing at the top. The mobile version or low-height screen is aligned to the top of the screen, while the desktop is center-page aligned.

Mobile:

image



Desktop: 

image

**Comment by rlouf** [comment]
I added some animated text. It does some funky stuff with the logo, but this is already much better than what we currently have so I'm merging. We can address remaining issues in a new PR.

**Comment by cpfiffer** [comment]
We should maybe consider removing the animated text -- it tends to annoy web people when elements move around and the site content is not immediately visible

**Pull request merged**
